<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Contracts\Responses\" />
    <Folder Include="Contracts\Requests\" />
    <Folder Include="Models\" />
    <Folder Include="Options\" />
    <Folder Include="Services\" />
    <Folder Include="Optimizers\" />
    <Folder Include="Providers\Geocoding\" />
    <Folder Include="Providers\Routing\" />
  </ItemGroup>

</Project>
